### ISSUE TITLE
前后端显示节点剩余数量不一致

### ISSUE THREAD

**Issue by gethin52** [huayu8/JDC#7]
例如：配置文件改为99，青龙后台只有30个cookie。前端页面显示剩余69个，但是京东扫码登录点击确定登录的时候提示节点数量不足
还有一个问题是在青龙后台禁用了账号，前端显示状态正常

**Comment by huayu8** [comment]
请更新到2.0.1版本，该版本已经修复了这个bug

**Comment by huayu8** [comment]
前端显示的状态只是cookie状态
