### ISSUE TITLE
执行./JDC出现报错

### ISSUE THREAD

**Issue by dengxiaozhen** [huayu8/JDC#9]
![image](https://user-images.githubusercontent.com/8529528/121157633-50153880-c87c-11eb-9435-f45abfef1583.png)
试过好几次了

**Comment by EdisonCC** [comment]
这个是你的安装路径问题

**Comment by dengxiaozhen** [comment]
> 这个是你的安装路径问题

指的是安装青龙控制面板的路径吗

**Comment by huayu8** [comment]
JDC与ql文件夹是同级关系 你的JDC放到了ql文件夹里，没注意看教程吧，我一直强调同级

**Comment by demon0318** [comment]
哪里有教程

**Comment by Liquid-w** [comment]
> > 这个是你的安装路径问题
> 
> 指的是安装青龙控制面板的路径吗？我看着路径也没错鸭
> ![image](https://user-images.githubusercontent.com/8529528/121288784-78517580-c916-11eb-8a79-f4716f40fc4e.png)

path那行改一下，改成 path = "/ql"

**Comment by dengxiaozhen** [comment]
> JDC与ql文件夹是同级关系 你的JDC放到了ql文件夹里，没注意看教程吧，我一直强调同级

多谢大佬 解决了👍

**Comment by dengxiaozhen** [comment]
> > > 这个是你的安装路径问题
> > 
> > 
> > 指的是安装青龙控制面板的路径吗？我看着路径也没错鸭
> > ![image](https://user-images.githubusercontent.com/8529528/121288784-78517580-c916-11eb-8a79-f4716f40fc4e.png)
> 
> path那行改一下，改成 path = "/ql"

你这个方法我试过了 不行
